### ISSUE TITLE
issues trying to use adxl345

### ISSUE THREAD

**Issue by VincentDugard** [dimalo/klipper-web-control-docker#54]
Hello, firstly thank you for this amazing repo

I'm trying to use adxl345 to configure inputshaper
i'm using a rpi4, latest docker image (even tried next tag and building manually)
My adxl345 unit is working properly, I tested spi mode using another software on the same rpi

First issue I got is 
```
Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). 
```
as a workaround I manually installed numpy in the venv directly in the container.

Then I get this error
```
Invalid adxl345 id (got 0 vs e5)
```

I put klipper's recommended configuration like this
```
[adxl345]
cs_pin: host:None

[resonance_tester]
accel_chip: adxl345
probe_points:
    110, 110, 20  # an example
```

I also tried multiple docker-compose config, using what you did in you adxl345 variant. Currently I have 
```
  klipper:
    image: dimalo/klipper-moonraker:next
    privileged: true
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    # if klipper cannot connect to the printer check permissions on rpi then add the group here
    group_add:
      - "996"
      - "998"
      - "5"
      - "20"
    cap_add:
      - ALL
    container_name: klipper
    ports:
      - 7125:7125
    restart: unless-stopped
    volumes:
      - /dev:/dev
      - gcode_files:/home/klippy/printer_data/gcodes
      # be aware to create your own branch if you mount the config folder as it will be updated on the main branch
      # that way you can merge upstream changes to your customized configs
      - ./config:/home/klippy/printer_data/config
      - moonraker_data:/home/klippy/.moonraker_database
      # - <<your_config_path>>:/home/klippy/.config
      # - ./printer.cfg:/home/klippy/.config/printer.cfg
    # mount serial device - take care to grant sufficient permissions to the device: <host_dev>:<container_dev>
    # put <container_dev> into your printer.cfg
    devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
 ```

as you can see I even tried privileged mode, mounting /dev directly but still I get that same error
Do you have any tips ? since you provide a specific docker-compose file for adxl345 I guess you succeed to use it ?
